# Generated by Django 3.2.9 on 2022-05-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='media/personal/')),
                ('address', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('post_desc', models.TextField()),
                ('fb_link', models.CharField(max_length=254)),
                ('linkedin_link', models.CharField(max_length=254)),
                ('insta_link', models.CharField(max_length=254)),
                ('twitter_link', models.CharField(max_length=254)),
                ('github_link', models.CharField(max_length=254)),
                ('about_myself', models.TextField()),
            ],
        ),
    ]
