# Generated by Django 3.2.9 on 2022-05-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='phone',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
