# Generated by Django 3.2.9 on 2022-05-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_personal_info_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='phone',
            field=models.PositiveBigIntegerField(),
        ),
    ]
